### ISSUE TITLE
The app can't handle when I tried to log in by filling every field empty.

### ISSUE THREAD

**Issue by sagorahmed** [AiursoftWeb/Kahla-Notify#7]
#### Expected behavior
I expected that the app would notify me or warn me when I click on the login after filling all fields blank.

#### Actual behavior
When I clicked on the login button after letting all fields empty, then the app crashes.

#### How to reproduce
Here is every possible detail to reproduce the bug.
1. Open the app.
2. The login page will arrive. Clear all the fields and click on the login.
3. Notice the error.

* App version: 2.0.2
* Operating system: Android 6.0.1

#### Recording Of The Bug
![kahla](https://media.giphy.com/media/KbN1aUZybcrAYCiun4/giphy.gif)
#### LogCat
```
05-26 13:43:00.241 27643 27643 E AndroidRuntime: FATAL EXCEPTION: main

05-26 13:43:00.241 27643 27643 E AndroidRuntime: Process: com.ganlvtech.kahlanotify, PID: 27643

05-26 13:43:00.241 27643 27643 E AndroidRuntime: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1333)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at okhttp3.HttpUrl.get(HttpUrl.java:916)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at com.ganlvtech.kahlanotify.kahla.BaseService.newHttpUrlBuilder(BaseService.java:27)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at com.ganlvtech.kahlanotify.kahla.BaseService.newRequestBuilder(BaseService.java:33)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at com.ganlvtech.kahlanotify.kahla.AuthService.newAuthByPasswordCall(AuthService.java:64)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at com.ganlvtech.kahlanotify.client.KahlaClient.login(KahlaClient.java:275)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at com.ganlvtech.kahlanotify.LoginActivity.login(LoginActivity.java:152)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at com.ganlvtech.kahlanotify.LoginActivity.access$200(LoginActivity.java:17)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at com.ganlvtech.kahlanotify.LoginActivity$5.onClick(LoginActivity.java:93)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at android.view.View.performClick(View.java:5714)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:10932)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22589)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

05-26 13:43:00.241 27643 27643 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by ganlvtech** [comment]
Download the latest prerelease and have a try. Have fun.

**Comment by sagorahmed** [comment]
Hi @ganlvtech 
Sorry for my late response.
This issue is not occurring anymore in the latest pre-release version.
Thanks for solving the issue.
